[workspace]
# If more Spin apps are added to the solution, they should be referenced here.
members = [    
    "apps/orderprocessor/receiver",
    "apps/orderprocessor/statusprovider",
    "apps/fulfilmentprocessor",
    "crates/order-management"
]