apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventprocessor
  template:
    metadata:
      labels:
        app: eventprocessor
    spec:
      runtimeClassName: wasmtime-spin
      containers:
        - name: eventprocessor
          image: eventprocessor:latest
          imagePullPolicy: Never
          command: ["/"]