---
apiVersion: v1
kind: Service
metadata:
  name: redis-stack
spec:
  type: NodePort
  ports:
    - name: redis-stack-server
      protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30002
    - name: redis-stack
      protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30010
  selector:
    app: redis-stack
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: redis-stack
#   annotations:
#     ingress.kubernetes.io/ssl-redirect: "false"
#     kubernetes.io/ingress.class: traefik
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: redis-stack
#                 port:
#                   number: 8001