name: Create and setup devcontainer
on:
  workflow_call:
jobs:
  build-devcontainer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: download code
      with:
        fetch-depth: 0
    - name: build the devcontainer image
      run: |
        docker build -t devcontainer -f .devcontainer/Dockerfile ./.devcontainer
    - name: run the devcontainer image
      run: |
        docker run --name devcontainer -d --rm --privileged --mount type=bind,source=${{ github.workspace}},target=/workspace devcontainer
    - name: install tools
      run: |
        docker exec devcontainer sh ./workspace/.devcontainer/bootstrap.sh
