name: Main Branch PR
on: 
  pull_request:
    branches:
      - main
jobs:
  Build-Code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: build the devcontainer image
      run: |
        docker build -t devcontainer -f .devcontainer/Dockerfile ./.devcontainer
    - name: run the devcontainer image
      run: |
        docker run --name devcontainer --rm --privileged --mount type=bind,source=${{GITHUB_WORKSPACE},target=/workspace devcontainer
    - name: install tools
      run: |
        docker exec -it devcontainer sh ./workspace/.devcontainer/bootstrap.sh
    - name: install cluster and workloads
      run: |
        docker exec -it devcontainer sh -c "cd ./workspace && make save_images"