name: Main - Upload Apps Images/Packages

on: 
  push:
    branches: 
      - main
    paths:
      # Only run this when apps are updated.
      - 'apps/**'
    
jobs:
  Release-Apps-Images:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: download code
      with:
        fetch-depth: 0
    - name: build the devcontainer image
      run: |
        docker build -t devcontainer -f .devcontainer/Dockerfile ./.devcontainer
    - name: run the devcontainer image
      run: |
        cd ..
        docker run --name devcontainer -d --rm --privileged --mount type=bind,source=${{ github.workspace }},target=/workspace devcontainer
    - name: install tools
      run: |
        docker exec devcontainer sh ./workspace/.devcontainer/bootstrap.sh
    - name: log in to the Container registry
      run: |
        docker exec devcontainer sh -c "docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}"
    - name: push workload images
      run: |
        docker exec devcontainer sh -c "export PATH="/root/.cargo/bin:$PATH" && cd ./workspace && make build_push_app_images GITHUBORG=${{ github.repository_owner }} GITHUBREPO=${{ github.repository }}"
