name: Main - Upload Apps Images/Packages

on: 
  push:
    branches: 
      - main
    paths:
      # Only run this when chart file is updated.
      - 'apps/**'

jobs:
  Release-Apps-Images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: download code
      with:
        fetch-depth: 0
    - name: build the devcontainer image
      run: |
        docker build -t devcontainer -f .devcontainer/Dockerfile ./.devcontainer
    - name: run the devcontainer image
      run: |
        cd ..
        docker run --name devcontainer -d --rm --privileged --mount type=bind,source=${{ github.workspace}},target=/workspace devcontainer
    - name: install tools
      run: |
        docker exec devcontainer sh ./workspace/.devcontainer/bootstrap.sh
    - name: save workload images
      run: |
        docker exec devcontainer sh -c "export PATH="/root/.cargo/bin:$PATH" && cd ./workspace && make build_save_app_images"
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: import images in host´s Docker
      run: |
        docker load --input ./artifacts/orderprocessor.tar
        docker load --input ./artifacts/fulfilmentprocessor.tar
    - name: get version and push image orderprocessor 
      run: |
        cd ./apps/orderprocessor
        VERSION=`grep ^version spin.toml | cut -d'"' -f 2`
        docker push orderprocessor:$VERSION
        docker push orderprocessor:latest
    - name: get version and push image fulfilmentprocessor 
      run: |
        cd ./apps/fulfilmentprocessor
        VERSION=`grep ^version spin.toml | cut -d'"' -f 2`
        docker push fulfilmentprocessor:$VERSION
        docker push fulfilmentprocessor:latest
